# Generated by Django 2.2.6 on 2019-11-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_translation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('language', models.CharField(default='en', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Product')),
            ],
            options={
                'db_table': 'product_translation',
            },
        ),
    ]
