# Generated by Django 2.2.6 on 2019-12-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='quantity',
            field=models.CharField(max_length=253),
        ),
    ]
