# Generated by Django 2.2.6 on 2019-10-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminrole',
            table='admins_rules',
        ),
        migrations.AlterModelTable(
            name='admins',
            table='admins',
        ),
        migrations.AlterModelTable(
            name='rules',
            table='rules',
        ),
    ]
