# Generated by Django 2.2.6 on 2019-11-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_product_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_images',
            old_name='iamge',
            new_name='image',
        ),
    ]
