# Generated by Django 2.2.6 on 2019-12-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20191201_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clien',
            new_name='client',
        ),
    ]
