# Generated by Django 2.2.6 on 2019-10-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20191028_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.DeleteModel(
            name='Permession',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(to='Admin.Permission'),
        ),
    ]
