# Generated by Django 2.2.6 on 2019-12-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20191201_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
