# Generated by Django 2.2.6 on 2019-10-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20191028_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
