# Generated by Django 2.2.6 on 2019-11-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
