# Generated by Django 2.2.6 on 2019-10-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20191028_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
