# Generated by Django 2.2.6 on 2019-10-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_auto_20191029_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='avatar.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
