# Generated by Django 2.2.6 on 2019-11-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_auto_20191122_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.TextField(null=True),
        ),
    ]
