# Generated by Django 2.2.6 on 2019-10-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_auto_20191029_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, default='avatar.png'),
        ),
    ]
