# Generated by Django 2.2.6 on 2019-10-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_auto_20191030_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='avatar.png', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(blank=True, to='Admin.Permission'),
        ),
    ]
