# Generated by Django 2.2.6 on 2019-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_auto_20191204_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='Admin.Order_product', to='Admin.Product'),
        ),
    ]
