# Generated by Django 2.2.6 on 2019-11-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_auto_20191101_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(blank=True, related_name='permissions', to='Admin.Permission'),
        ),
    ]
