# Generated by Django 2.2.6 on 2019-11-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_auto_20191101_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
