# Generated by Django 2.2.6 on 2019-11-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_user_register_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Admin',
        ),
    ]
