# Generated by Django 2.2.6 on 2019-11-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_category_category_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_en',
            old_name='category_id',
            new_name='category',
        ),
    ]
