# Generated by Django 2.2.6 on 2019-11-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_auto_20191108_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_en',
            name='desc_image',
        ),
        migrations.AddField(
            model_name='category',
            name='desc_image',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Category_ar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Category')),
            ],
            options={
                'db_table': 'categories_ar',
            },
        ),
    ]
