# Generated by Django 2.2.6 on 2019-11-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_auto_20191111_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_en',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category_ar',
        ),
        migrations.DeleteModel(
            name='Category_en',
        ),
    ]
