# Generated by Django 2.2.6 on 2019-11-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_auto_20191111_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_translation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Category')),
            ],
        ),
    ]
