# Generated by Django 2.2.6 on 2019-11-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_category_translation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category_translation',
            table='categories_translation',
        ),
    ]
