# Generated by Django 2.2.6 on 2019-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_auto_20191111_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_translation',
            name='language',
            field=models.CharField(default='en', max_length=255),
        ),
    ]
